### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by tomkinsc** [miketaylr/urlgrep#7]
Would it be possible to clarify the license for code in this repo? Thanks!

**Comment by miketaylr** [comment]
Oh yeah, let me add one real quick.

@tomkinsc is MIT OK? I don't really have a preference.

**Comment by miketaylr** [comment]
Actually, let me just make it CC0, since the code I forked was declared as such as well.

https://github.com/cpinto/python-webpage-inliner/issues/2

**Comment by miketaylr** [comment]
Here ya go: https://github.com/miketaylr/urlgrep#license
