### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cpinto** [miketaylr/urlgrep#8]
Mike, I've added the license file to the original repository. It'd be awesome if you could update your fork. Also, if you have any code fixes I'll be happy to merge them via a PR. Thanks.

**Comment by miketaylr** [comment]
Sounds good @cpinto -- I just added a CC0 license yesterday, but I'm happy to pull in your LICENSE file as it's effectively the same thing.

As for a PR, it's been a long time since I've looked at the code. Maybe when I run out of more pressing things to do I'll take a stab. :)

**Comment by cpinto** [comment]
No rush :) I'll close this too
